# Use postgres/example user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db_transaction'
      MYSQL_USER: 'db_username'
      MYSQL_PASSWORD: 'db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_volume:/var/lib/mysql
      - ./db_volume/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - transactional-network

  transactional-api:
    image: transaction-api:local
    container_name: transaction-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=db_transaction
      - DB_USER=db_username
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=db_password
      - HOST=0.0.0.0
      - BASE_PATH=/transactional/api
      - APPLICATION_NAME=transactional-api
      - ENVIRONMENT=dev
      - SERVER_PORT=8080
      - APP_DEFAULT_HOST=0.0.0.0
    networks:
      - transactional-network

volumes:
  db_volume:
    driver: local

networks:
  transactional-network:
    driver: bridge