# Use postgres/example user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db_transactional'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_volume:/var/lib/mysql
      - "./db_volume/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db_volume/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      - transactional-network

  transactional-api:
    container_name: transaction-api
    restart: always
    build: transactional-api/
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=db_transactional
      - DB_USER=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=root
      - HOST=0.0.0.0
      - BASE_PATH=/transactional/api
      - APPLICATION_NAME=transactional-api
      - ENVIRONMENT=dev
      - SERVER_PORT=8080
      - APP_DEFAULT_HOST=0.0.0.0
    networks:
      - transactional-network

  account-api:
    container_name: account-api
    restart: always
    build: account-api/
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      - DB_NAME=db_transactional
      - DB_USER=root
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_PASSWORD=root
      - HOST=0.0.0.0
      - BASE_PATH=/account/api
      - APPLICATION_NAME=account-api
      - ENVIRONMENT=dev
      - SERVER_PORT=8080
      - APP_DEFAULT_HOST=0.0.0.0
    networks:
      - transactional-network

volumes:
  db_volume:
    driver: local

networks:
  transactional-network:
    driver: bridge